### ISSUE TITLE
Not picking up courses in this output

### ISSUE THREAD

**Issue by Fogest** [Fogest/Course2iCal#14]
A user reported a problem importing their courses from the following paste:

```
Skip to Main Content
 University of Guelph
 Office of Registrarial Services
 WebAdvisor for REDACTED L.
 University of Guelph-Humber Logo
 Help
 Students Menu
 Main Menu
 Log Out
 Have a question? Ask Gryph!
  
 Schedule
 Class Schedule GridExam Schedule Grid
 1234567 Redacted Name
 
 Term
 Fall 2019
 
 Total Registered Credits	
 2.25
 
 Course Name and Title	Status	Meeting Information	Creds	CEUs	Pass Aud	Start Date ENGG*4230*0102 (3003) Energy Conversion
 Selected
 
 LEC Tues, Thur
 08:30AM - 09:50AM
 ALEX, Room 218
 LAB Thur
 10:00AM - 12:50PM
 THRN, Room 2336
 LAB Thur
 10:00AM - 12:50PM
 THRN, Room 3402
 LAB Thur
 10:00AM - 12:50PM
 THRN, Room 3404
 0.75
 
 19/09/05
 
 ENGG*3700*0101 (2984) Optimization for Engineers
 Selected
 
 LEC Mon, Wed, Fri
 09:30AM - 10:20AM
 MCLN, Room 102
 LAB Wed
 07:00PM - 08:50PM
 ALEX, Room 259
 EXAM Fri
 07:00PM - 09:00PM (2019/12/13)
 Room TBA
 0.50
 
 19/09/05
 
 ENGG*3080*0103 (2878) Energy Resources & Tech.
 Selected
 
 LEC Tues, Thur
 01:00PM - 02:20PM
 MCKN, Room 029
 LAB Thur
 03:30PM - 05:20PM
 THRN, Room 3404
 EXAM Thur
 08:30AM - 10:30AM (2019/12/05)
 Room TBA
 0.50
 
 19/09/05
 
 ENGG*3070*0101 (2873) Integrated Manuf Systems
 Selected
 
 LEC Mon, Wed, Fri
 11:30AM - 12:20PM
 RICH, Room 2529
 LAB Tues
 02:30PM - 04:20PM
 THRN, Room 1007
 LAB Tues
 02:30PM - 04:20PM
 THRN, Room 1313
 EXAM Mon
 02:30PM - 04:30PM (2019/12/02)
 Room TBA
 0.50
 
 19/09/05
 
 ENGG*4000*01 (2988) Proposal Engineering Design IV
 Selected
 
 LEC Days TBA
 Times TBA
 Room TBA
 0.00
 
 19/09/05
 
 If you require a student record or information on program requirements in an alternate format, please contact ups@uoguelph.ca .
 
 University of Guelph
 50 Stone Road East
 Guelph, Ontario, N1G 2W1
 Canada
 519-824-4120
 © Office of Registrarial Services

**Comment by Fogest** [comment]
@Coteh I can look at this on Monday but if you are bored feel free to take a look at this earlier :)

**Comment by Coteh** [comment]
Looks like the browser the user copied their schedule from prepends a space before each line (except for the first line). The Regex that picks up the lecture times (`getCourseTime:232`) does not like this, so it'll need to be updated.

**Comment by Fogest** [comment]
This was copied from what someone sent me on Facebook so it is possible that caused the formatting issue but I can't confirm that at the moment.

**Comment by Coteh** [comment]
Good point. If you're able to pick up the exact same text the user input into the textarea let me know. I imagine it's available in the logs, no?

**Comment by Fogest** [comment]
Yeah here it is from the logs. Appears to have no spaces:

```
Request:
Skip to Main Content
University of Guelph
Office of Registrarial Services
WebAdvisor for Removed N.
University of Guelph-Humber Logo
Help
Students Menu
Main Menu
Log Out
Have a question? Ask Gryph!

Schedule
Class Schedule GridExam Schedule Grid
1234567 Removed Name

Term
Fall 2019

Total Registered Credits
2.25

Course Name and Title   Status  Meeting Information     Creds   CEUs    Pass Aud        Start Date
ENGG*4230*0102 (3003) Energy Conversion
Selected

LEC Tues, Thur
08:30AM - 09:50AM
ALEX, Room 218
LAB Thur
10:00AM - 12:50PM
THRN, Room 2336
LAB Thur
10:00AM - 12:50PM
THRN, Room 3402
LAB Thur
10:00AM - 12:50PM
THRN, Room 3404
0.75

19/09/05

ENGG*3700*0101 (2984) Optimization for Engineers
Selected

LEC Mon, Wed, Fri
09:30AM - 10:20AM
MCLN, Room 102
LAB Wed
07:00PM - 08:50PM
ALEX, Room 259
EXAM Fri
07:00PM - 09:00PM (2019/12/13)
Room TBA
0.50

19/09/05

ENGG*3080*0103 (2878) Energy Resources & Tech.
Selected

LEC Tues, Thur
01:00PM - 02:20PM
MCKN, Room 029
LAB Thur
03:30PM - 05:20PM
THRN, Room 3404
EXAM Thur
08:30AM - 10:30AM (2019/12/05)
Room TBA
0.50

19/09/05

ENGG*3070*0101 (2873) Integrated Manuf Systems
Selected

LEC Mon, Wed, Fri
11:30AM - 12:20PM
RICH, Room 2529
LAB Tues
02:30PM - 04:20PM
THRN, Room 1007
LAB Tues
02:30PM - 04:20PM
THRN, Room 1313
EXAM Mon
02:30PM - 04:30PM (2019/12/02)
Room TBA
0.50

19/09/05

ENGG*4000*01 (2988) Proposal Engineering Design IV
Selected

LEC Days TBA
Times TBA
Room TBA
0.00

19/09/05

If you require a student record or information on program requirements in an alternate format, please contact ups@uoguelph.ca .

University of Guelph
50 Stone Road East
Guelph, Ontario, N1G 2W1
Canada
519-824-4120
© Office of Registrarial Services

**Comment by Coteh** [comment]
I was able to successfully download a .ics file of their schedule using both Chrome 76 and Firefox 69 (edit: works on Safari 12.1.2 too). Did the user provide any other info? Were they able to get to this step?

**Comment by Fogest** [comment]
I will have to reach out to them and get more information. I just tested and it did work for me as well.

**Comment by Coteh** [comment]
Some other things I noticed:
- ENGG\*4230 and ENGG\*3070 have multiple labs at the same time but in different rooms, but this shouldn't cause any issue
- ENGG\*4000 is completely TBA on their schedule. Judging from the title of the course, it's probably not meant to have a room nor time, it could just be a slot in their calendar for their fourth year project. `convertArrayOfDatesToICSFormat` and `getCourseTime` seem to handle the TBA corner cases adequately though.

**Comment by Fogest** [comment]
The user stated they were using Chrome on Windows 10. That is exactly what I tested with and had no issues. Seems odd that they had any problems especially considering the logged content is exactly what they would have submitted and that worked fine.

**Comment by Fogest** [comment]
It sounds like the problem is when they go to import the ics file into Google Calendar. They get an error with 0 of 0 imported events.

**Comment by Coteh** [comment]
Can confirm, that is indeed the case.

<img width="324" alt="image" src="https://user-images.githubusercontent.com/3276350/64493598-0f742f80-d250-11e9-93dd-056b6d77703d.png">

Will take a look into it further.

**Comment by Coteh** [comment]
Removed `BYDAY=Days of the week incorrect` clause from the TBA event seemed to fix it. Get 15 of 15 events imported now.

<img width="324" alt="image" src="https://user-images.githubusercontent.com/3276350/64493647-ae009080-d250-11e9-9dab-8b7fffabaa87.png">

**Comment by Coteh** [comment]
I believe that the fix can be as simple as removing `BYDAY` rule from events with "TBA Date". I can work on a fix when I get home.

**Comment by Fogest** [comment]
Sounds awesome! I can take a look at the fix tomorrow if you don't get time
today.
