### ISSUE TITLE
Website does not respond when clicking generate calendar

### ISSUE THREAD

**Issue by HugoKlepsch** [Fogest/Course2iCal#8]
Maybe webadvisor changed, but I copy pasted the class schedule page with Ctl-A and pasted with Ctl-V. 

When I clicked on generate, nothing happened at all, no download button as shown in the video.

**Comment by HugoKlepsch** [comment]
Here is what I pasted:

```
Skip to Main Content
University of Guelph
Office of Registrarial ServicesWebAdvisor for Hugo
University of Guelph-Humber Logo

    Help
    Students Menu
    Main Menu
    Log Out

Have a question? Ask Gryph!
Schedule
Class Schedule Grid
Exam Schedule Grid



Term

Fall 2016
Total Registered Credits    

2.50
Course Name and Title   Status  Meeting Information Creds   CEUs    Pass Aud    Start Date
COOP*1100*04 (5804) Introduction to Coop Education


Selected

LEC Tues
04:30PM - 05:20PM
THRN, Room 1307


0.00




P


16/09/08
CIS*3250*0102 (5771) Software Design III


Selected

LEC Mon, Wed, Fri
11:30AM - 12:20PM
MCKN, Room 029
LAB Fri
02:30PM - 05:20PM
REYN, Room 114


0.50






16/09/08
CIS*2520*0101 (5755) Data Structures


Selected

LEC Tues, Thur
02:30PM - 03:50PM
ROZH, Room 103
LAB Mon
02:30PM - 04:20PM
MCKN, Room 238


0.50






16/09/08
CIS*2430*0102 (5746) Object Oriented Programming


Selected

LEC Mon, Wed, Fri
12:30PM - 01:20PM
MACN, Room 105
LAB Tues
12:30PM - 02:20PM
THRN, Room 2420


0.50






16/09/08
CIS*2030*0104 (5739) Structure/Applicat - Microcomp


Selected

LEC Mon, Wed, Fri
01:30PM - 02:20PM
ALEX, Room 200
LAB Thur
05:30PM - 08:20PM
THRN, Room 2420


0.50






16/09/08
PSYC*1000*02 (7639) Introduction to Psychology


Selected

LEC Tues, Thur
10:00AM - 11:20AM
ROZH, Room 104


0.50






16/09/08

If you require a student record or information on program requirements in an alternate format, please contact ups@uoguelph.ca .
University of Guelph
50 Stone Road East
Guelph, Ontario, N1G 2W1
Canada
519-824-4120

© Office of Registrarial Services
```

**Comment by Fogest** [comment]
@HugoKlepsch I edited your comment so that it is in the code quotes, however I still think the format may be off. Could you comment again the schedule using the proper code formatting so that github doesn't mess it up? The style guide is here: https://guides.github.com/features/mastering-markdown/

I also am using a service that tracks when people get an error when trying to use the site and I do see that it looks like there is an error around getting the course time. It is getting errors in the area where it would be figuring out the courses start time. So once I have a copy of the correctly formatted content you are pasting into the site I can do some more debugging!

**Comment by HugoKlepsch** [comment]
It may be worth noting that this is for next fall's schedule, and some courses may be TBD on some fields. 
The following is directly from the paste, now formatted. 

```
Skip to Main Content
University of Guelph
Office of Registrarial ServicesWebAdvisor for Hugo
University of Guelph-Humber Logo

    Help
    Students Menu
    Main Menu
    Log Out

Have a question? Ask Gryph!
Schedule
Class Schedule Grid
Exam Schedule Grid



Term

Fall 2016
Total Registered Credits    

2.50
Course Name and Title   Status  Meeting Information Creds   CEUs    Pass Aud    Start Date
COOP*1100*04 (5804) Introduction to Coop Education


Selected

LEC Tues
04:30PM - 05:20PM
THRN, Room 1307


0.00




P


16/09/08
CIS*3250*0102 (5771) Software Design III


Selected

LEC Mon, Wed, Fri
11:30AM - 12:20PM
MCKN, Room 029
LAB Fri
02:30PM - 05:20PM
REYN, Room 114


0.50






16/09/08
CIS*2520*0101 (5755) Data Structures


Selected

LEC Tues, Thur
02:30PM - 03:50PM
ROZH, Room 103
LAB Mon
02:30PM - 04:20PM
MCKN, Room 238


0.50






16/09/08
CIS*2430*0102 (5746) Object Oriented Programming


Selected

LEC Mon, Wed, Fri
12:30PM - 01:20PM
MACN, Room 105
LAB Tues
12:30PM - 02:20PM
THRN, Room 2420


0.50






16/09/08
CIS*2030*0104 (5739) Structure/Applicat - Microcomp


Selected

LEC Mon, Wed, Fri
01:30PM - 02:20PM
ALEX, Room 200
LAB Thur
05:30PM - 08:20PM
THRN, Room 2420


0.50






16/09/08
PSYC*1000*02 (7639) Introduction to Psychology


Selected

LEC Tues, Thur
10:00AM - 11:20AM
ROZH, Room 104


0.50






16/09/08

If you require a student record or information on program requirements in an alternate format, please contact ups@uoguelph.ca .
University of Guelph
50 Stone Road East
Guelph, Ontario, N1G 2W1
Canada
519-824-4120

© Office of Registrarial Services
```

**Comment by Fogest** [comment]
Hmm this is weird. The formatting of your output looks different than what my paste would look like. Mine ends up having no blank lines at all. And I'm wondering what that random looking single `p` is for in your coop course section. However it looks like the program is correctly figuring out each course still. 

I am going to look at the parsing I am doing for the times area, but I have a feeling it may have something to do with that `p`. In your webadvisor do you know what that `p` character that seems to be randomly there represents? I don't have a coop course so I have never seen that.

**Comment by HugoKlepsch** [comment]
I couldn't tell you right now what that p is (afk), maybe it's one of my plugins? 

I use Firefox with uBlock origin.

**Comment by HugoKlepsch** [comment]
I found what the p is! 
It seems they added a new column to the table. 
![tmp_32430-screenshot_20160330-191006843482175](https://cloud.githubusercontent.com/assets/12129001/14160586/2d8e34c2-f6ab-11e5-8253-053fbfa05339.png)

**Comment by Fogest** [comment]
Shouldn't be uBlock here. I use uBlock as well. So I did some debugging and in a majority of the cases, when someone goes to use the tool there paste does not have a bunch of extra blank lines in it. Like when I look at mine for example it does not contain these blank new lines. 

Also, it looks like that `P` caused issues too. I am not sure what the `pass aud` is and if it was in web advisor before, but I'll make some changes to my code to hopefully fix this problem for the future. 

For now however I did alter your paste so that it works on the site. The only changes I made were removing the extra blank lines, and removing the line with the P. This is essentially what I am going to make my site automatically do in order to fix this problem, however the fix is not implemented yet, so for now you can just use this version of your schedule on the site:

```
Skip to Main Content
University of Guelph
Office of Registrarial ServicesWebAdvisor for Hugo
University of Guelph-Humber Logo
    Help
    Students Menu
    Main Menu
    Log Out
Have a question? Ask Gryph!
Schedule
Class Schedule Grid
Exam Schedule Grid
Term
Fall 2016
Total Registered Credits    
2.50
Course Name and Title   Status  Meeting Information Creds   CEUs    Pass Aud    Start Date
COOP*1100*04 (5804) Introduction to Coop Education
Selected
LEC Tues
04:30PM - 05:20PM
THRN, Room 1307
0.00
16/09/08
CIS*3250*0102 (5771) Software Design III
Selected
LEC Mon, Wed, Fri
11:30AM - 12:20PM
MCKN, Room 029
LAB Fri
02:30PM - 05:20PM
REYN, Room 114
0.50
16/09/08
CIS*2520*0101 (5755) Data Structures
Selected
LEC Tues, Thur
02:30PM - 03:50PM
ROZH, Room 103
LAB Mon
02:30PM - 04:20PM
MCKN, Room 238
0.50
16/09/08
CIS*2430*0102 (5746) Object Oriented Programming
Selected
LEC Mon, Wed, Fri
12:30PM - 01:20PM
MACN, Room 105
LAB Tues
12:30PM - 02:20PM
THRN, Room 2420
0.50
16/09/08
CIS*2030*0104 (5739) Structure/Applicat - Microcomp
Selected
LEC Mon, Wed, Fri
01:30PM - 02:20PM
ALEX, Room 200
LAB Thur
05:30PM - 08:20PM
THRN, Room 2420
0.50
16/09/08
PSYC*1000*02 (7639) Introduction to Psychology
Selected
LEC Tues, Thur
10:00AM - 11:20AM
ROZH, Room 104
0.50
16/09/08
If you require a student record or information on program requirements in an alternate format, please contact ups@uoguelph.ca .
University of Guelph
50 Stone Road East
Guelph, Ontario, N1G 2W1
Canada
519-824-4120

© Office of Registrarial Services
```

**Comment by Fogest** [comment]
The commit I referenced there has now fixed the problem by removing blank lines from the whatever is inputted as well as removing the line with only a `P` on it as it does not seem relevant to the data.
